### ISSUE TITLE
vim-nightly daily updating task is not working

### ISSUE THREAD

**Issue by palopezv** [ScoopInstaller/Main#2948]
vim-nightly updating task stopped working around October 31. Neovim-nightly works Ok. What gives?

**Comment by issaclin32** [comment]
The *Excavator* bot was blocked by Github because of too many requests. (too many packages are being updated)
This should be automatically solved in a few hours.

https://scoop.r15.ch/main/mud-20211114-160001.log
`vim-nightly: The remote server returned an error: (429) too many requests.`

**Comment by palopezv** [comment]
@niheaven Still doesn't work, see https://scoop.r15.ch/main/mud-20211117-140001.log And BTW, the neovim-nightly is now borked due to #2960

**Comment by run2cmd** [comment]
This still seems to be not solved. Yesterday we got VIM release 8.2.3692 but I do not see bucket was updated.
