### ISSUE TITLE
Python pip update botched

### ISSUE THREAD

**Issue by denioma** [ScoopInstaller/Main#3135]
After installing the latest python from scoop I did a routine pip upgrade and this was the result:
```
Requirement already satisfied: pip in c:\users\rod-k\scoop\persist\python\lib\site-packages (21.2.4)
Collecting pip
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
  WARNING: Failed to write executable - trying to use .deleteme logic
  Rolling back uninstall of pip
  Moving to c:\users\rod-k\scoop\persist\python\lib\site-packages\pip-21.2.4.dist-info\
   from C:\Users\rod-k\scoop\persist\python\Lib\site-packages\~ip-21.2.4.dist-info
  Moving to c:\users\rod-k\scoop\persist\python\lib\site-packages\pip\
   from C:\Users\rod-k\scoop\persist\python\Lib\site-packages\~ip
  Moving to c:\users\rod-k\scoop\persist\python\scripts\
   from C:\Users\rod-k\scoop\persist\python\~cripts
ERROR: Could not install packages due to an OSError: [WinError 3] O sistema não conseguiu localizar o caminho especificado: 'C:\\Users\\rod-k\\scoop\\apps\\python\\current\\Scripts\\pip.exe' -> 'C:\\Users\\rod-k\\scoop\\apps\\python\\current\\Scripts\\pip.exe.deleteme'

WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the 'C:\Users\rod-k\scoop\apps\python\current\python.exe -m pip install --upgrade pip' command.
```

Pip then stayed at version 21.2.4 while reporting that it is already updated, but paths differ:
```
~ ❯ python3 -m pip --version
pip 21.2.4 from C:\Users\rod-k\scoop\apps\python\current\lib\site-packages\pip (python 3.10)
~ ❯ python3 -m pip install -U pip
Requirement already satisfied: pip in c:\users\rod-k\scoop\persist\python\lib\site-packages (21.3.1)
```

**Comment by rashil2000** [comment]
This was fixed recently. You might need to reinstall pip packages. See https://github.com/ScoopInstaller/Main/issues/3095

**Comment by graphixillusion** [comment]
I'm still having this problem with the last version comes out today.

**Comment by rashil2000** [comment]
You will have to reinstall pip packages after this change

**Comment by rashil2000** [comment]
What is the error? Try deleting the ~/scoop/persist/python folder, and then reinstall python from Scoop. And then your pip packages.

**Comment by graphixillusion** [comment]
Ok following this procedure it worked:
1. Uninstall python 
2. Delete persist
3. Install python
4. Install pip with get-pip.py

Previously it doesn't work becouse between step 3 and 4 i was uninstalling existing pip manually before try to install the new one.
