### ISSUE TITLE
imagemagick@7.1.0-48: decompress error

### ISSUE THREAD

**Issue by syffs** [ScoopInstaller/Main#3964]
#### Scoop Configuration

```json
{
    "SCOOP_BRANCH":  "master",
    "SCOOP_REPO":  "https://github.com/ScoopInstaller/Scoop",
    "lastupdate":  "2022-09-24T02:59:26.7515869+02:00"
}
```

**Comment by rashil2000** [comment]
![image](https://user-images.githubusercontent.com/46838874/192082186-347ea807-74fb-4450-8e57-46e4f6ae3c31.png)


Please clear your cache and try again

**Comment by syffs** [comment]
![image](https://user-images.githubusercontent.com/4192037/192087645-c66303e4-1132-4c8c-ab50-186f199333c5.png)
same issue

**Comment by rashil2000** [comment]
What's in the log?

**Comment by syffs** [comment]
```
Signature detected: Inno Setup Setup Data (6.1.0) (u)
This is not directly supported, but i'll try to unpack it as version 6000
; Version detected: 6100 (Unicode)
Unpacking failed. This version is not supported.
```

**Comment by rashil2000** [comment]
Can you try `scoop install imagemagick-lean`?

**Comment by syffs** [comment]
```
Installing 'imagemagick-lean' (7.1.0) [64bit] from main bucket
ImageMagick-7.1.0-portable-Q16-HDRI-x64.zip (111,3 MB) [==========================================================================================] 100%
Checking hash of ImageMagick-7.1.0-portable-Q16-HDRI-x64.zip ... ERROR Hash check failed!
App:         main/imagemagick-lean
URL:         https://imagemagick.org/archive/binaries/ImageMagick-7.1.0-portable-Q16-HDRI-x64.zip
First bytes: 50 4B 03 04 14 00 08 00
Expected:    d9295e32bd90bb4b9b8b2816b4662533770adac1f5e4189c5cb97dec7e1bbc4c
Actual:      d86fe565d2767b469f92db4181582ee835985fc32cbc0be5c66b250118e3c26a

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=imagemagick-lean%407.1.0%3a+hash+check+failed
```

**Comment by rashil2000** [comment]
Fixed in https://github.com/ScoopInstaller/Main/commit/b43ff9882b5d1aa57fd7687db9549baaf55881a8

Can you try again?

**Comment by syffs** [comment]
Thanks! it now works with `imagemagick-lean`, still the same with `imagemagick` tho
